# Generated by Django 4.0.6 on 2022-10-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampaignName', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('CampaignStatus', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WA_MSG_Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_id', models.CharField(default='', max_length=50)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('token', models.CharField(default='', max_length=255)),
                ('business_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
        migrations.CreateModel(
            name='Voice_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_API', models.CharField(default='', max_length=255)),
                ('header', models.JSONField(blank=True, max_length=255, null=True)),
                ('whatsapp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('u_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=12)),
                ('received_msg', models.CharField(blank=True, max_length=1000, null=True)),
                ('received_time', models.DateTimeField()),
                ('is_read', models.BooleanField(default=0)),
                ('reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('send_time', models.DateTimeField(null=True)),
                ('reply_number', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=10, null=True)),
                ('json', models.JSONField(max_length=1000, null=True)),
                ('request', models.CharField(max_length=255, null=True)),
                ('response', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('speechFile', models.CharField(blank=True, max_length=50, null=True)),
                ('Voice_API', models.CharField(blank=True, max_length=50, null=True)),
                ('voiceshoot_req', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceshoot_res', models.JSONField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('recordID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='user_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1'),
        ),
    ]
