# Generated by Django 4.0.6 on 2022-10-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_data_summary_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='reply_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='sender_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user1',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
