# Generated by Django 4.0.6 on 2022-10-11 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_callback_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('send_time', models.DateTimeField(null=True)),
                ('reply_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10, null=True)),
                ('request', models.CharField(max_length=255, null=True)),
                ('response', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
    ]
