# Generated by Django 4.0.6 on 2022-10-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('gen_time', models.DateTimeField(blank=True, null=True)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=20, null=True)),
                ('message_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wa_msg_provider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
    ]
