# Generated by Django 4.0.6 on 2022-10-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_developers_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
