# Generated by Django 4.0.6 on 2022-10-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_outbox_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbox',
            name='to_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
