# Generated by Django 4.1.2 on 2022-10-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_outbox_to_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbox',
            name='msg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
