# Generated by Django 4.1.2 on 2022-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_data_summary_voice_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback_data',
            name='msg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callback_data',
            name='msg_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
