# Generated by Django 4.1.2 on 2022-10-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_callback_data_msg_id_callback_data_msg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='msg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='msg_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
