# Generated by Django 4.1.2 on 2022-10-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_messagelog_msg_id_messagelog_msg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='msg_status',
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lang_code', models.CharField(blank=True, max_length=15, null=True)),
                ('is_media', models.BooleanField(blank=True)),
                ('message_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wa_msg_provider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
    ]
