# Generated by Django 4.1.2 on 2022-10-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers_token',
            name='med_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
