# Generated by Django 4.1.2 on 2022-10-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_developers_token_med_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='temp_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
