# Generated by Django 4.1.2 on 2022-10-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_conversation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation_status',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1'),
        ),
    ]
