# Generated by Django 4.1.2 on 2022-10-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_conversation_status_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_summary',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
