# Generated by Django 4.1.2 on 2022-10-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_data_summary_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
