# Generated by Django 4.1.2 on 2022-11-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user1_is_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation_status',
            name='provider',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='reply_number',
            field=models.CharField(max_length=100),
        ),
    ]
