# Generated by Django 4.1.2 on 2022-11-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_conversation_status_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='variables',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
