# Generated by Django 4.1.2 on 2022-11-05 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_templates_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampaignName', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('CampaignStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('user_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
    ]
