# Generated by Django 4.1.2 on 2022-11-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_advancecampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=20, null=True)),
                ('variables', models.CharField(blank=True, max_length=1000, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceshoot_req', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceshoot_res', models.JSONField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('what_status', models.CharField(max_length=10, null=True)),
                ('recordID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.campaign')),
            ],
        ),
    ]
