# Generated by Django 4.1.2 on 2022-11-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_advance_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance_data',
            name='recordID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.advancecampaign'),
        ),
    ]
