# Generated by Django 4.1.2 on 2022-11-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_advance_data_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance_data',
            name='variables',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
