# Generated by Django 4.1.2 on 2022-11-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_advance_data_variables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developers_token',
            options={'verbose_name_plural': 'Developer_Token'},
        ),
        migrations.AlterModelOptions(
            name='user1',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='wa_msg_provider',
            options={'verbose_name_plural': 'WA_MSG_Provider'},
        ),
        migrations.CreateModel(
            name='SubMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=15)),
                ('received_msg', models.CharField(blank=True, max_length=1000, null=True)),
                ('received_time', models.DateTimeField()),
                ('reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('send_time', models.DateTimeField(null=True)),
                ('reply_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10, null=True)),
                ('json', models.JSONField(max_length=1000, null=True)),
                ('request', models.CharField(max_length=255, null=True)),
                ('response', models.CharField(max_length=1000, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
    ]
