# Generated by Django 4.1.2 on 2022-11-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_developers_token_options_alter_user1_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submessagelog',
            name='received_msg',
        ),
        migrations.RemoveField(
            model_name='submessagelog',
            name='received_time',
        ),
        migrations.RemoveField(
            model_name='submessagelog',
            name='sender_number',
        ),
        migrations.AddField(
            model_name='submessagelog',
            name='parent_msg_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.messagelog'),
        ),
    ]
