# Generated by Django 4.1.2 on 2022-11-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_remove_submessagelog_received_msg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submessagelog',
            old_name='parent_msg_id',
            new_name='parent_msg',
        ),
    ]
