# Generated by Django 4.1.2 on 2022-11-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_rename_parent_msg_id_submessagelog_parent_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance_data',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
