# Generated by Django 4.1.2 on 2022-11-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_what_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Auto_Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_message', models.CharField(max_length=1000, null=True)),
                ('reply_message', models.CharField(max_length=1000, null=True)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.what_bot')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wa_msg_provider')),
            ],
        ),
    ]
