# Generated by Django 4.1.2 on 2022-11-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_bot_auto_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_auto_reply',
            name='reply_message',
            field=models.JSONField(null=True),
        ),
    ]
