# Generated by Django 4.1.2 on 2022-11-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_bot_auto_reply_reply_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBotStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(max_length=15, null=True)),
                ('provider_name', models.CharField(max_length=100, null=True)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.what_bot')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wa_msg_provider')),
            ],
        ),
    ]
