# Generated by Django 4.1.2 on 2022-11-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_customerbotstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_auto_reply',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
