# Generated by Django 4.1.2 on 2022-11-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_bot_auto_reply_show_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_auto_reply',
            name='msg_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
