# Generated by Django 4.1.2 on 2022-11-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_bot_auto_reply_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wa_msg_provider',
            name='temp_footer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wa_msg_provider',
            name='temp_header',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
