# Generated by Django 4.1.2 on 2022-11-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_wa_msg_provider_temp_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Templtes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('text_msg', models.CharField(blank=True, max_length=1000, null=True)),
                ('text_converted', models.CharField(blank=True, max_length=1000, null=True)),
                ('lang_code', models.CharField(blank=True, max_length=15, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('temp_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('message_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wa_msg_provider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
    ]
