# Generated by Django 4.1.2 on 2022-11-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_new_templtes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_Templtes',
            new_name='New_Templates',
        ),
    ]
