# Generated by Django 4.1.2 on 2022-11-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_outbox_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbox',
            name='media_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
