# Generated by Django 4.1.2 on 2022-11-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_alter_outbox_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='validity',
            field=models.DateField(null=True),
        ),
    ]
