# Generated by Django 4.1.2 on 2022-12-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_user1_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance_data',
            name='msg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callback_data',
            name='msg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data_summary',
            name='msg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='msg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='msg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='submessagelog',
            name='msg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
