# Generated by Django 4.1.2 on 2022-12-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_alter_advance_data_msg_id_alter_callback_data_msg_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('both', models.BooleanField(null=True)),
                ('whatsapp', models.BooleanField(null=True)),
                ('sms', models.BooleanField(null=True)),
            ],
        ),
    ]
