# Generated by Django 4.1.2 on 2022-12-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_sms_settings_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_settings',
            name='sms_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
