# Generated by Django 4.1.2 on 2022-12-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_sms_settings_keywords_sms_settings_sel_sms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissMatched_Temps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_msg', models.CharField(max_length=1000, null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wa_msg_provider')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
    ]
