# Generated by Django 4.1.2 on 2022-12-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_alter_new_templates_text_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='APP_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
