# Generated by Django 4.1.2 on 2022-12-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_alter_app_setting_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation_status',
            name='inbox_msg',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation_status',
            name='received_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='send_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
