# Generated by Django 4.1.2 on 2022-12-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_alter_conversation_status_inbox_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='validity',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
