# Generated by Django 4.1.2 on 2022-12-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_alter_user1_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_setting',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
