# Generated by Django 4.1.2 on 2022-12-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_app_setting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='received_msg',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='reply_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
