# Generated by Django 4.1.2 on 2022-12-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_message_history_api_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_history',
            name='msg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
