# Generated by Django 4.1.2 on 2022-12-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_message_history_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_history',
            name='cust_receive_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='message_history',
            name='read_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='message_history',
            name='sent_time',
            field=models.DateTimeField(null=True),
        ),
    ]
