# Generated by Django 4.1.2 on 2022-12-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_message_history_cust_receive_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_history',
            old_name='cust_receive_time',
            new_name='delivered_time',
        ),
    ]
