# Generated by Django 4.1.2 on 2022-12-20 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_rename_cust_receive_time_message_history_delivered_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('valid_till', models.IntegerField(default=8)),
                ('user_vice', models.BooleanField(default=0)),
                ('provider_vice', models.BooleanField(default=0)),
                ('provider_cus_pair', models.BooleanField(default=0)),
                ('campaign_vice', models.BooleanField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
    ]
