# Generated by Django 4.1.2 on 2022-12-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_whatsapp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp_token',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wa_msg_provider'),
        ),
    ]
