# Generated by Django 4.1.2 on 2022-12-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_whatsapp_token_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp_token',
            name='adv_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.advancecampaign'),
        ),
        migrations.AddField(
            model_name='whatsapp_token',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.campaign'),
        ),
        migrations.AddField(
            model_name='whatsapp_token',
            name='customer_num',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
