# Generated by Django 4.1.2 on 2022-12-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_whatsapp_token_adv_campaign_whatsapp_token_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.CharField(blank=True, max_length=200)),
                ('temp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lang_code', models.CharField(blank=True, max_length=15, null=True)),
                ('med_id', models.CharField(blank=True, max_length=255, null=True)),
                ('json', models.JSONField(null=True)),
                ('message_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wa_msg_provider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
    ]
