# Generated by Django 4.1.2 on 2022-12-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_chat_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_templates',
            name='temp_preview',
            field=models.JSONField(null=True),
        ),
    ]
