# Generated by Django 4.1.2 on 2022-12-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_chat_templates_is_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_templates',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
