# Generated by Django 4.1.2 on 2022-12-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_chat_templates_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='media_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='submessagelog',
            name='media_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
