# Generated by Django 4.1.2 on 2022-12-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0079_messagelog_media_content_submessagelog_media_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday_temp', models.IntegerField(null=True)),
                ('anyversary_temp', models.IntegerField(null=True)),
                ('scheduled_time', models.TimeField(null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
                ('wap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wa_msg_provider')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_mobile', models.CharField(max_length=15, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('anyversary', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('setting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.reminder_setting')),
            ],
        ),
    ]
