# Generated by Django 4.1.2 on 2022-12-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0080_reminder_setting_reminder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder_user',
            old_name='anyversary',
            new_name='anniversary',
        ),
    ]
