# Generated by Django 4.1.2 on 2022-12-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0081_rename_anyversary_reminder_user_anniversary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder_setting',
            name='anyversary_temp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reminder_setting',
            name='birthday_temp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
