# Generated by Django 4.1.2 on 2022-12-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0082_alter_reminder_setting_anyversary_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder_user',
            name='a_sent',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='reminder_user',
            name='b_sent',
            field=models.BooleanField(default=0),
        ),
    ]
