# Generated by Django 4.1.2 on 2022-12-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0083_reminder_user_a_sent_reminder_user_b_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder_user',
            name='a_sent',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reminder_user',
            name='b_sent',
            field=models.DateField(null=True),
        ),
    ]
