# Generated by Django 4.1.2 on 2022-12-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0084_alter_reminder_user_a_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder_user',
            name='a_msg_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reminder_user',
            name='a_status',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reminder_user',
            name='b_msg_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reminder_user',
            name='b_status',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
