# Generated by Django 4.1.2 on 2023-01-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_user1_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.staff'),
        ),
    ]
