# Generated by Django 4.1.2 on 2023-01-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0090_user1_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='staff',
        ),
    ]
