# Generated by Django 4.1.2 on 2023-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0092_user1_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='is_mark_for_delete',
            field=models.BooleanField(default=False),
        ),
    ]
