# Generated by Django 4.1.2 on 2023-01-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0093_user1_is_mark_for_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_templates',
            name='has_button',
            field=models.BooleanField(default=0),
        ),
    ]
