# Generated by Django 4.1.2 on 2023-01-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0094_new_templates_has_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
