from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login, name='login'),
    path('send_SMS', views.send_SMS, name='send_SMS'),
    path('send_Template', views.send_Template, name='send_Template'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('addCamp/', views.addCamp, name='addCamp'),
    path('AddComposer/', views.addComposer, name='addCompo'),
    path('preview/', views.preview_composer, name='previewCompo'),
    path('process/', views.process_composer, name='processCompo'),
    path('composerList/', views.record, name='composerList'),
    path('startCamp/', views.start, name='startCamp'),
    path('settings/', views.settings, name='settings'),
    path('logout/', views.logout, name='logout'),
    path('start_all/', views.start_all, name='start_all'),
    path('stop/', views.stop, name='stop'),
    path('DownloadZip/', views.DownloadZip, name='DownloadZip'),
    path('pendingAll/', views.pendingAll, name='pendingAll'),
    path('resetPass/', views.resetPass, name='resetPass'),
    path('delete/', views.delete, name='delete'),
    path('deleteAll/', views.deleteAll, name='deleteAll'),
    path('deleteRec/', views.deleteRec, name='deleteRec'),
    path('addSettings/', views.addSettings, name='addSettings'),
    path('editSettings/', views.editSettings, name='editSettings'),
    path('delete_setting/', views.delete_setting, name='delete_setting'),
    path('fetch_Temp/', views.fetch_Temp, name='fetch_Temp'),
    path('export_excel/', views.export_excel, name='export_excel'),
    path('setAllTemp/', views.setAllTemp, name='setAllTemp'),
    path('receive_msg/', views.receive_msg, name='receive_msg'),
    path('showMessages/', views.showMessages, name='showMessages'),
    path('send_message_panel/', views.send_message_panel, name='send_message_panel'),
    path('send_message/', views.send_message, name='send_message'),
    path('submessage_panel/', views.submessage_panel, name='submessage_panel'),
    path('check/', views.check, name='check'),
    path('searchTable/', views.searchTable, name='searchTable'),
    path('outBox/', views.outBox, name='outBox'),
    path('generateToken/', views.generateToken, name='generateToken'),
    path('refresh_temp/', views.refresh_temp, name='refresh_temp'),
    path('updateTokenTemp/', views.updateTokenTemp, name='updateTokenTemp'),
    path('manageTemplate/', views.manageTemplate, name='manageTemplate'),
    path('customerStat/', views.customerStat, name='customerStat'),
    path('advanceTemplate', views.advanceTemplate, name='advanceTemplate'),
    path('advanceCamp', views.advanceCamp, name='advanceCamp'),
    path('advanceRecord', views.advanceRecord, name='advanceRecord'),
    path('advanceStart', views.advanceStart, name='advanceStart'),
    path('getHeaderExcel', views.getHeaderExcel, name='getHeaderExcel'),
    path('advancePreview', views.advancePreview, name='advancePreview'),
    path('botSettings', views.botSettings, name='botSettings'),
    path('button_status', views.button_status, name='button_status'),
    path('toggle_bot', views.toggle_Bot_Stat, name='toggle_Bot_Stat'),
    path('addMesPair', views.addMesPair, name='addMesPair'),
    path('export_selected_excel', views.export_selected_excel, name='export_selected_excel'),
    path('getExcel', views.getExcel, name='getExcel'),
    path('customerBotState', views.customerBotState, name='customerBotState'),
    path('stopBot', views.stopBot, name='stopBot'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)